apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-deployment-system.fullname" . }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-deployment-system.fullname" . }}
  labels:
    app: {{ include "my-deployment-system.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-deployment-system.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-deployment-system.fullname" . }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}