image:
  repository: ghcr.io/brscherer/server
  tag: "latest"
replicaCount: 1
service:
  type: ClusterIP
  port: 3001
  metricsPort: 9100
livenessProbe:
  path: /health
  port: 3001
  initialDelaySeconds: 15
  periodSeconds: 10
readinessProbe:
  path: /health
  port: 3001
  initialDelaySeconds: 5
  periodSeconds: 5
